In [96]:
import pandas as pd

df=pd.DataFrame(
    {'Rollno':[1,1,2,2,1,2],
    'Subject':['DS','Java','DS','Java','DS','Java'],
    'Marks':[25,40,30,26,40,50],
    'Date':['01-01-23','02-02-23','01-01-23','02-01-23','15-01-23','15-01-23']}
    )

In [97]:
df

   Rollno Subject  Marks      Date
0       1      DS     25  01-01-23
1       1    Java     40  02-02-23
2       2      DS     30  01-01-23
3       2    Java     26  02-01-23
4       1      DS     40  15-01-23
5       2    Java     50  15-01-23

In [98]:
df['Date']=pd.to_datetime(df['Date'],format='%d-%m-%y')
df['Date']

0   2023-01-01
1   2023-02-02
2   2023-01-01
3   2023-01-02
4   2023-01-15
5   2023-01-15
Name: Date, dtype: datetime64[ns]

In [99]:
df=df.sort_values('Date',ascending=False)
df

   Rollno Subject  Marks       Date
1       1    Java     40 2023-02-02
4       1      DS     40 2023-01-15
5       2    Java     50 2023-01-15
3       2    Java     26 2023-01-02
0       1      DS     25 2023-01-01
2       2      DS     30 2023-01-01

In [100]:
g=df.groupby(['Rollno','Subject'])

In [101]:
marks=g['Marks'].apply(lambda x:(list(x.head(2))+[0,0,0])[:3])
outputdf=pd.DataFrame(marks.tolist(),index=marks.index,columns=['M1','M2','M3'])
outputdf

                M1  M2  M3
Rollno Subject
1      DS       40  25   0
       Java     40   0   0
2      DS       30   0   0
       Java     50  26   0

In [102]:
outputdf['Date']=g['Date'].max().dt.strftime('%d-%m-%y')

outputdf=outputdf.reset_index()
print(outputdf)

   Rollno Subject  M1  M2  M3      Date
0       1      DS  40  25   0  15-01-23
1       1    Java  40   0   0  02-02-23
2       2      DS  30   0   0  01-01-23
3       2    Java  50  26   0  15-01-23